### ISSUE TITLE
Added some functionality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [romainallain/pykismetkml#11]
```
I've added some functionality (filter encryption modes) and own preferences 
(full data also in the placemarks description).

And fixed some minor bugs (do not apcount++ for non-infrastructure networks 
which won't be added, corrected last printed).

See attachment.
```

Original issue reported on code.google.com by `der.hede.342@gmail.com` on 2 Oct 2013 at 8:25

Attachments:
- [pykismetkml-2010-02-R1.py](https://storage.googleapis.com/google-code-attachments/pykismetkml/issue-11/comment-0/pykismetkml-2010-02-R1.py)

**Comment by romainallain** [comment]
integrated
